-- 把 demo-one-customer-each.sql 改掉的 debtor 名字和合约的 DebtorCode 放回去（由改动前的实际资料生成，2026-09-12）。可以重跑。
SET NOCOUNT ON;
UPDATE dbo.Debtor SET CompanyName = N'ARENA STABIL SDN. BHD.' WHERE AccNo = '3000-A0005';
UPDATE dbo.Debtor SET CompanyName = N'ASIAMOST SDN BHD' WHERE AccNo = '3000-A0014';
UPDATE dbo.Debtor SET CompanyName = N'ARCHIBINA' WHERE AccNo = '3000-A0023';
UPDATE dbo.Debtor SET CompanyName = N'ARHITECT HARIANI' WHERE AccNo = '3000-A0051';
UPDATE dbo.Debtor SET CompanyName = N'AIRPAY MALAYSIA SDN. BHD.' WHERE AccNo = '3000-A0071';
UPDATE dbo.Debtor SET CompanyName = N'AGREE SPORT ENTERPRISE' WHERE AccNo = '3000-A0073';
UPDATE dbo.Debtor SET CompanyName = N'ARENA STABIL SDN. BHD.' WHERE AccNo = '3000-A0074';
UPDATE dbo.Debtor SET CompanyName = N'ARENA STABIL SDN. BHD.' WHERE AccNo = '3000-A0087';
UPDATE dbo.Debtor SET CompanyName = N'ARENA STABIL SDN. BHD.' WHERE AccNo = '3000-A0090';
UPDATE dbo.Debtor SET CompanyName = N'ARENA STABIL SDN. BHD.' WHERE AccNo = '3000-A0179';
UPDATE dbo.Debtor SET CompanyName = N'ARENA STABIL SDN. BHD.' WHERE AccNo = '3000-A0199';
UPDATE dbo.Debtor SET CompanyName = N'ARENA STABIL SDN. BHD' WHERE AccNo = '3000-A0213';
UPDATE dbo.Debtor SET CompanyName = N'FASTROCOM (MALAYSIA) SDN BHD' WHERE AccNo = '3000-F0019';
UPDATE dbo.Debtor SET CompanyName = N'IDEAL MELATI SDN BHD' WHERE AccNo = '3000-I0001';
UPDATE dbo.Debtor SET CompanyName = N'JURUKUR HARTAMAS SDN BHD' WHERE AccNo = '3000-J0026';
UPDATE dbo.Debtor SET CompanyName = N'JABATAN PERLINDUNGAN HIDUPAN LIAR' WHERE AccNo = '3000-J0056';
UPDATE dbo.Debtor SET CompanyName = N'KENSINGTON GREEN SPECIALIST CENTRE' WHERE AccNo = '3000-K0011';
UPDATE dbo.Debtor SET CompanyName = N'LINKBUILD SDN BHD' WHERE AccNo = '3000-L0003';
UPDATE dbo.Debtor SET CompanyName = N'MULTI GREEN ENGINEERING SDN BHD' WHERE AccNo = '3000-M0001';
UPDATE dbo.Debtor SET CompanyName = N'PUSAT TUISYEN GAMMA GENIUS' WHERE AccNo = '3000-P0013';
UPDATE dbo.Debtor SET CompanyName = N'SINGLE ADVERTISING & TRADING SDN BHD' WHERE AccNo = '3000-S0027';
UPDATE dbo.Debtor SET CompanyName = N'SYNTURN (M) SDN BHD' WHERE AccNo = '3000-S0033';
UPDATE dbo.Debtor SET CompanyName = N'SKY ACTIVE SDN. BHD.' WHERE AccNo = '3000-S0136';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-A0074' WHERE ContractNo = N'DEMO-3G';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-A0074' WHERE ContractNo = N'DEMO-DUTY';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-F0019' WHERE ContractNo = N'DEMO-F19';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-A0179' WHERE ContractNo = N'DEMO-HSI';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-I0001' WHERE ContractNo = N'DEMO-IKT';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-A0199' WHERE ContractNo = N'DEMO-IPG';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-J0056' WHERE ContractNo = N'DEMO-J56';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-S0136' WHERE ContractNo = N'DEMO-JPJ';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-K0011' WHERE ContractNo = N'DEMO-KEN';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-L0003' WHERE ContractNo = N'DEMO-KJR';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-A0074' WHERE ContractNo = N'DEMO-KKR';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-J0026' WHERE ContractNo = N'DEMO-KST';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-A0074' WHERE ContractNo = N'DEMO-MBJB';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-M0001' WHERE ContractNo = N'DEMO-MRA';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-A0005' WHERE ContractNo = N'DEMO-PG';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-A0074' WHERE ContractNo = N'DEMO-PL';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-A0074' WHERE ContractNo = N'DEMO-PL2';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-A0090' WHERE ContractNo = N'DEMO-PON';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-P0013' WHERE ContractNo = N'DEMO-PPM';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-A0074' WHERE ContractNo = N'DEMO-SA';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-S0027' WHERE ContractNo = N'DEMO-SGL';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-S0033' WHERE ContractNo = N'DEMO-SYN';
UPDATE dbo.zSCP2_Contract SET DebtorCode = '3000-A0213' WHERE ContractNo = N'DEMO-TGK';
